/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/household": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The household record */
        get: operations["getHousehold"];
        put: operations["replaceHousehold"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put: operations["replaceSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The ordered levels, and which nests under which */
        get: operations["listLevels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pillars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPillars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The attribute catalog
         * @description Attributes with `pillar: null` are descriptive: nothing scores them, and they exist to
         *     make a candidate legible (`reqs.md` 3.3).
         */
        get: operations["listAttributes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attributes/{attributeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAttribute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDataSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{candidateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A candidate with its descriptive attributes */
        get: operations["getCandidate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stored values, with full provenance
         * @description Returns the active value per attribute by default. `include_superseded` returns every
         *     value from every source, which is what the drill-down shows — nothing is ever discarded
         *     (`reqs.md` 3.6).
         */
        get: operations["listValues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/values/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enter a value by hand
         * @description Manual entry is a real source, ranked last, and **permitted only where the attribute
         *     declares it** (`reqs.md` 6.5). It is how a figure with no adapter gets recorded, and how
         *     an early estimate is captured so a real dataset can supersede it later without deleting
         *     anything.
         *
         *     Rejected with `409 manual_entry_not_permitted` when the attribute does not allow it.
         */
        post: operations["enterValueManually"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/criteria-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCriteriaSets"];
        put?: never;
        post: operations["createCriteriaSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/criteria-sets/{criteriaSetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCriteriaSet"];
        put?: never;
        post?: never;
        delete: operations["deleteCriteriaSet"];
        options?: never;
        head?: never;
        patch: operations["renameCriteriaSet"];
        trace?: never;
    };
    "/criteria-sets/{criteriaSetId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy a criteria set
         * @description The safe way to experiment — a drag edits a set in place (`reqs.md` Q168).
         */
        post: operations["duplicateCriteriaSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/criteria-sets/{criteriaSetId}/criteria/{attributeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Adjust one criterion
         * @description Changing `weight` **rebalances the unlocked siblings within the pillar**, honouring locks,
         *     so the pillar always sums to 1. The response returns every criterion in that pillar with
         *     its new weight — the client sends one number and is told what the others became
         *     (`arch.md` 8.3).
         */
        patch: operations["updateCriterion"];
        trace?: never;
    };
    "/criteria-sets/{criteriaSetId}/pillar-weights/{pillarId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updatePillarWeight"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/criteria-sets/{criteriaSetId}/match-rules/{matchRuleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Whether this set enforces a gate */
        put: operations["setMatchRuleEnforcement"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/criteria-sets/{criteriaSetId}/compound-rules/{compoundRuleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Whether this set applies a compound rule */
        put: operations["setCompoundRuleApplication"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMatchRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match-rule-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMatchRuleResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match-rule-results/{matchRuleId}/{candidateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Record or override a gate's answer
         * @description Also how a candidate is ruled out by hand — the `not_manually_excluded` rule with a
         *     reason (`reqs.md` Q152). An override is audited and travels with the candidate.
         */
        put: operations["putMatchRuleResult"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compound-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCompoundRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-acquisition-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRuns"];
        put?: never;
        /**
         * Start a run
         * @description Returns immediately; the work happens in the background. Poll the run.
         */
        post: operations["startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-acquisition-runs/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Estimate a run without executing it
         * @description The dry run of `reqs.md` 6.3 — planned work and estimated cost, for confirmation before
         *     anything is fetched or spent. Has no side effects despite being a POST, because the
         *     scope is a body rather than a query.
         */
        post: operations["planRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-acquisition-runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A run, with live progress */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-acquisition-runs/{runId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry only what failed
         * @description Creates a **new** run whose scope is exactly the failures of this one.
         */
        post: operations["retryRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compute a ranking
         * @description **Computes and returns; stores nothing.** This is how "adjusting a weight recalculates
         *     instantly" works over HTTP (`reqs.md` 5.6, Q155). To keep a result, `POST /evaluations`.
         */
        get: operations["getRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvaluations"];
        put?: never;
        /**
         * Keep a ranking
         * @description Persists the ranking **with a frozen copy of the criteria used** and the per-attribute
         *     detail behind every score, so it reads the same later however the criteria set or the
         *     scoring code change (`reqs.md` 3.4a, Q156).
         */
        post: operations["saveEvaluation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvaluation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluationId}/candidates/{candidateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Why this candidate scored what it scored
         * @description The drill-down. Every attribute's normalised score, its effective weight after
         *     redistribution, its contribution, and **the exact value used**, with that value's source
         *     and dates. This is the provenance chain end to end.
         */
        get: operations["getCandidateScoreDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluationId}/criteria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The criteria this evaluation was computed with
         * @description The frozen snapshot (`reqs.md` 3.4a). The criteria set it names stays editable, so this
         *     is the only record of what the weights actually were when the ranking was produced — and
         *     which attributes were in scope, which is what keeps its coverage figure meaningful.
         */
        get: operations["getEvaluationCriteria"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A focus candidate against comparators
         * @description Levels are never mixed. The comparator limit comes from settings.
         */
        get: operations["getComparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Published scores from outside indices
         * @description Displayed **beside** the score, never fed into it (`reqs.md` 3.5a).
         */
        get: operations["listExternalScores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "code": "weights_all_locked",
         *       "message": "Every other weight in this pillar is locked.",
         *       "details": {
         *         "locked": [
         *           "country.income_tax_effective"
         *         ]
         *       }
         *     }
         */
        Error: {
            /** @description Stable and machine-readable. Branch on this, never on the message. */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        /** @description The span the data describes. Start equals end for a single day. */
        ReferencePeriod: {
            /** Format: date */
            start: string;
            /** Format: date */
            end: string;
        };
        FxRate: {
            rate: number;
            /** Format: date */
            rate_date: string;
            data_source: string;
        };
        Level: {
            id: string;
            depth_order: number;
            parent_level?: string | null;
        };
        Pillar: {
            id: string;
            name: string;
            description?: string;
        };
        /** @enum {string} */
        ValueTypeName: "Monetary" | "Quantity" | "Count" | "Ratio" | "Index" | "LabelSet" | "ShareComposition" | "Boolean" | "AssignedScore" | "Text";
        Attribute: {
            id: string;
            name: string;
            description?: string;
            level: string;
            /** @description Null for descriptive attributes, which are never scored. */
            pillar?: string | null;
            value_type: components["schemas"]["ValueTypeName"];
            unit?: string | null;
            /** @description How stale a figure may be before a fresher one outranks it, in whole months. Null means never. */
            max_age_months?: number | null;
            /** @description Whether a value may be typed by hand for this attribute. */
            manual_entry?: boolean;
            breakdown_scheme?: string | null;
            breakdown_options?: string[];
            /** @description Per-attribute validation beyond what the value type enforces. Null when none is declared. */
            allowed_range?: null | {
                min_value?: number | null;
                max_value?: number | null;
            };
            /** @description The controlled vocabulary a LabelSet may draw from. Empty when unconstrained. */
            allowed_labels?: string[];
            /** @description The order sources are consulted for this attribute, highest first: the attribute's own overrides, then every other source in the global order beneath them. Resolved on the server so no client reimplements the rule. */
            effective_source_priority?: string[];
        };
        DataSource: {
            id: string;
            name: string;
            /** @enum {string} */
            source_kind: "structured" | "llm" | "manual";
            default_priority: number;
            reliability_tier: string;
        };
        Candidate: {
            id: string;
            name: string;
            level: string;
            parent_candidate?: string | null;
        };
        CandidateDetail: components["schemas"]["Candidate"] & {
            /** @description Attributes with no criterion — population, timezone, coastline. */
            descriptive_values?: components["schemas"]["Value"][];
        };
        MonetaryPayload: {
            amount: number;
            /** @description ISO 4217 */
            currency: string;
            amount_eur: number;
            fx_rate?: components["schemas"]["FxRate"];
        };
        QuantityPayload: {
            magnitude: number;
            unit: string;
        };
        CountPayload: {
            count: number;
            basis?: string | null;
        };
        RatioPayload: {
            value: number;
            basis?: string | null;
        };
        IndexPayload: {
            value: number;
            provider: string;
            scale_min: number;
            scale_max: number;
        };
        LabelSetPayload: {
            labels: string[];
        };
        ShareCompositionPayload: {
            shares: {
                label: string;
                share: number;
            }[];
        };
        BooleanPayload: {
            value: boolean;
        };
        AssignedScorePayload: {
            value: number;
            range_min: number;
            range_max: number;
            /** @enum {string} */
            assigned_by: "llm" | "human";
            rationale?: string;
        };
        TextPayload: {
            body: string;
        };
        /** @description One measurement, with its provenance. `value_type` selects which variant `payload` holds. */
        Value: {
            id: number;
            candidate: string;
            attribute: string;
            breakdown_option?: string | null;
            value_type: components["schemas"]["ValueTypeName"];
            payload: components["schemas"]["MonetaryPayload"] | components["schemas"]["QuantityPayload"] | components["schemas"]["CountPayload"] | components["schemas"]["RatioPayload"] | components["schemas"]["IndexPayload"] | components["schemas"]["LabelSetPayload"] | components["schemas"]["ShareCompositionPayload"] | components["schemas"]["BooleanPayload"] | components["schemas"]["AssignedScorePayload"] | components["schemas"]["TextPayload"];
            data_source: string;
            reference_period: components["schemas"]["ReferencePeriod"];
            /** Format: date-time */
            retrieval_date: string;
            /** @enum {string} */
            confidence_level: "absolute" | "high" | "medium" | "low";
            /** @description Derived, not stored — the value scoring would use. */
            is_active: boolean;
            rejection_reason?: string | null;
            quote?: string | null;
            citations?: string[];
            data_acquisition_run?: number | null;
        };
        /** @description The source is implicitly `manual`; it cannot be set to anything else here. */
        ManualValueInput: {
            candidate: string;
            attribute: string;
            breakdown_option?: string | null;
            /** @description Must match the attribute's declared value type, or the request is rejected. */
            payload: components["schemas"]["MonetaryPayload"] | components["schemas"]["QuantityPayload"] | components["schemas"]["CountPayload"] | components["schemas"]["RatioPayload"] | components["schemas"]["IndexPayload"] | components["schemas"]["LabelSetPayload"] | components["schemas"]["ShareCompositionPayload"] | components["schemas"]["BooleanPayload"] | components["schemas"]["AssignedScorePayload"] | components["schemas"]["TextPayload"];
            reference_period: components["schemas"]["ReferencePeriod"];
            /** Format: date-time */
            retrieval_date: string;
            /**
             * @description Defaults to a deliberately unflattering middle; a source tier says nothing useful about a typed value (`reqs.md` 5.7).
             * @default medium
             * @enum {string}
             */
            confidence_level: "absolute" | "high" | "medium" | "low";
            /** @description Where this came from, in words. */
            quote?: string | null;
            citations?: string[];
        };
        HouseholdInput: {
            net_income: number;
            number_adults: number;
            /** @description Under 18. */
            number_children: number;
            target_monthly_spend?: number;
            max_rent?: number;
            home_country_candidate: string;
            home_city_candidate?: string | null;
            /** @description Candidate ids of countries. At least one is required: eu_free_movement and the UK and Swiss gates all turn on it (reqs.md 7.3), and an empty set would make every such gate pass or fail silently rather than visibly. */
            citizenships: string[];
        };
        Household: components["schemas"]["HouseholdInput"];
        SettingsInput: {
            /** @description Percentage, 0-100. Below this a candidate is insufficient_data rather than scored. */
            min_coverage?: number;
            score_scale_max?: number;
            comparator_limit?: number;
            run_spend_cap_eur?: number;
        };
        Settings: components["schemas"]["SettingsInput"];
        /** @description Only the fields present are changed. */
        CriterionInput: {
            is_scored?: boolean;
            /** @description Percentage, 0-100. Weights sum to 100 within a pillar, and pillar weights sum to 100 within a level. */
            weight?: number;
            weight_locked?: boolean;
            /** @enum {string} */
            goal?: "minimise" | "maximise" | "target_range";
            target_range_min?: number | null;
            target_range_max?: number | null;
            zero_score_below?: number | null;
            zero_score_above?: number | null;
            /** @enum {string} */
            normalisation_method?: "fixed" | "percentile" | "as_is";
            blocks_if_missing?: boolean;
            breakdown_option?: string | null;
            /**
             * @description Omit when the attribute has no breakdown.
             * @enum {string}
             */
            reducer_mode?: "select" | "aggregate";
            /** @description For the `fixed` method. A label lets a number display as a word without ceasing to be a number (`reqs.md` 5.1). */
            scale_anchors?: {
                input_value: number;
                score: number;
                /** @description e.g. affordable, stretching */
                label?: string | null;
            }[];
            /** @description Shape depends on the attribute's value type. Null clears it. */
            matching_threshold?: null | {
                min_value?: number | null;
                max_value?: number | null;
            } | {
                labels?: {
                    label: string;
                    /** @enum {string} */
                    containment_rule: "must_contain" | "must_not_contain";
                }[];
            } | {
                required_value?: boolean;
            } | {
                label?: string;
                min_share?: number | null;
                max_share?: number | null;
            };
        };
        Criterion: components["schemas"]["CriterionInput"] & {
            attribute: string;
            pillar: string;
        };
        /** @description A criterion as it stood when an evaluation ran, not as it stands now. The criteria set it was copied from stays editable, so this is the only record of the interpretation that produced the scores (reqs.md 3.4a, Q193). */
        EvaluationCriterion: components["schemas"]["Criterion"] & {
            /** @description The anchors frozen at the moment the evaluation ran, label included -- re-reading an old evaluation must show the words it showed then. */
            scale_anchors?: {
                input_value?: number;
                score?: number;
                /** @description The word this band displays as, from this anchor up to the next. */
                label?: string | null;
            }[];
        };
        PillarWeight: {
            pillar: string;
            /** @description Percentage, 0-100. Pillar weights sum to 100 within a level. */
            weight: number;
            weight_locked: boolean;
        };
        CriteriaSetSummary: {
            id: string;
            name: string;
        };
        CriteriaSet: components["schemas"]["CriteriaSetSummary"] & {
            pillar_weights?: components["schemas"]["PillarWeight"][];
            criteria?: components["schemas"]["Criterion"][];
            enforced_match_rules?: string[];
            applied_compound_rules?: string[];
        };
        MatchRule: {
            id: string;
            name: string;
            level: string;
        };
        MatchRuleResultInput: {
            /** @enum {string} */
            match_result: "matching" | "not_matching" | "unknown";
            reason?: string;
            /** @default manual */
            data_source: string;
            reference_period?: components["schemas"]["ReferencePeriod"];
            /** Format: date-time */
            retrieval_date?: string;
            override_reason?: string | null;
        };
        MatchRuleResult: components["schemas"]["MatchRuleResultInput"] & {
            match_rule: string;
            candidate: string;
            /** @description The pages this verdict was read from. A gate decided by manual or LLM-assisted research carries the same obligation to show its sources that a value does (reqs.md 3.7, 6.9). */
            citations?: string[];
            /** Format: date-time */
            override_date?: string | null;
        };
        CompoundRule: {
            id: string;
            name: string;
            level: string;
            /** @enum {string} */
            shape: "ShareOfHouseholdField" | "SumBelowFloor" | "AllConditionsHold";
            /** @enum {string} */
            outcome: "warning" | "not_matching";
            threshold_min?: number | null;
            threshold_max?: number | null;
            /** @description In order. Each is an attribute or a household field. Used by ShareOfHouseholdField and SumBelowFloor, which take their thresholds at rule level. */
            inputs: {
                input_order?: number;
                attribute?: string | null;
                household_field?: string | null;
            }[];
            /** @description Used by AllConditionsHold. Each names one attribute and its own band, in that attribute's own unit; the rule fires when every condition holds. A null bound is unbounded on that side. AND is the only connective and it is implicit in the shape, so there is deliberately no operator field -- see reqs.md 3.7a. */
            conditions?: {
                ordinal?: number;
                attribute?: string;
                threshold_min?: number | null;
                threshold_max?: number | null;
            }[];
        };
        RunScope: {
            level: string;
            /** @description Null means every candidate at the level. */
            candidates?: string[] | null;
            /** @description Null means every attribute at the level. */
            attributes?: string[] | null;
        };
        RunPlan: {
            items_total: number;
            llm_call_count: number;
            estimated_cost_eur: number;
            by_source?: {
                data_source?: string;
                items?: number;
            }[];
        };
        Run: {
            id: number;
            /** @enum {string} */
            run_status: "running" | "completed" | "halted_on_spend_cap" | "failed";
            triggered_by?: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at?: string | null;
            llm_call_count?: number;
            cost_eur?: number;
        };
        RunDetail: components["schemas"]["Run"] & {
            scope?: components["schemas"]["RunScope"];
            progress?: {
                items_total?: number;
                items_completed?: number;
                items_failed?: number;
            };
            failures?: {
                candidate: string;
                attribute: string;
                error_message: string;
            }[];
        };
        Warning: {
            compound_rule: string;
            detail: string;
        };
        /** @description Exactly one of criterion, match_rule or compound_rule is set. */
        NonMatchReason: {
            /** @description The attribute whose matching threshold was crossed. */
            criterion?: string | null;
            match_rule?: string | null;
            compound_rule?: string | null;
            reason_detail: string;
        };
        CandidateResult: {
            candidate: string;
            name: string;
            /** @description Null when the candidate does not match. */
            rank?: number | null;
            /** @description Null only when insufficient data. */
            score: number | null;
            /** @description Why this candidate could not be scored, in words -- a blocking criterion with no figure, or coverage below the floor. Null whenever there is a score. Separate from non_match_reasons, which say why a candidate that COULD be scored does not match: "we could not measure this" and "we measured it and it fails" are different things to show. */
            insufficient_reason?: string | null;
            /** @description Percentage, 0-100. The share of active weight actually backed by data. */
            coverage: number;
            /** @description How the covered weight splits by confidence (`reqs.md` 5.7). Coverage alone cannot show that a candidate reached 100% entirely on extrapolation; this can. */
            coverage_by_confidence?: {
                absolute?: number;
                high?: number;
                medium?: number;
                low?: number;
            };
            /** @enum {string} */
            match_status: "matching" | "not_matching" | "insufficient_data";
            parent_not_matching?: boolean;
            warnings?: components["schemas"]["Warning"][];
            non_match_reasons?: components["schemas"]["NonMatchReason"][];
            /** @description The country's score, shown beside a city for context. Never added in. */
            parent_score?: number | null;
        };
        Ranking: {
            /** @description Set when this is a saved evaluation rather than a live computation. */
            evaluation?: number | null;
            criteria_set: string;
            level: string;
            /** Format: date-time */
            computed_at: string;
            candidates: components["schemas"]["CandidateResult"][];
        };
        EvaluationSummary: {
            id: number;
            criteria_set: string;
            level: string;
            /** Format: date-time */
            computed_at: string;
            /** @description The top of the score range this evaluation used, frozen with it. Read scores against this rather than against the current setting, which may since have changed. */
            score_scale_max: number;
            note?: string | null;
        };
        AttributeScore: {
            attribute: string;
            pillar: string;
            /** @description Null when no value was available. */
            normalised_score: number | null;
            /** @description Percentage, 0-100. Weight within the pillar as configured. */
            weight?: number;
            /** @description Percentage, 0-100. After redistribution for missing data. */
            effective_weight: number;
            contribution: number;
            value?: components["schemas"]["Value"];
            /** @description Every other stored value for this attribute — superseded, rejected, from other sources. */
            alternative_values?: components["schemas"]["Value"][];
        };
        CandidateScoreDetail: components["schemas"]["CandidateResult"] & {
            attribute_scores?: components["schemas"]["AttributeScore"][];
        };
        ComparisonAttributeRow: {
            attribute: string;
            pillar?: string;
            focus: {
                value?: components["schemas"]["Value"];
                normalised_score?: number | null;
            };
            comparators?: {
                candidate?: string;
                value?: components["schemas"]["Value"];
                normalised_score?: number | null;
                /** @description Focus minus comparator, in the attribute's own unit. */
                delta?: number | null;
                /** @description What the delta is worth. Drives the synthesis. */
                weighted_contribution?: number | null;
            }[];
        };
        Comparison: {
            criteria_set: string;
            level: string;
            focus: components["schemas"]["CandidateResult"];
            comparators: components["schemas"]["CandidateResult"][];
            attributes: components["schemas"]["ComparisonAttributeRow"][];
            /** @description Templated from weighted contributions, never model-written. Deterministic. */
            synthesis?: {
                comparator?: string;
                score_delta?: number;
                advantages?: string[];
                disadvantages?: string[];
            }[];
        };
        ExternalScore: {
            candidate: string;
            data_source: string;
            published_value?: number | null;
            published_scale: string;
            published_rank?: number | null;
            published_rank_of?: number | null;
            reference_period?: components["schemas"]["ReferencePeriod"];
            /** Format: date-time */
            retrieval_date?: string;
            /** Format: uri */
            methodology_url?: string | null;
            caveats?: string | null;
        };
    };
    responses: {
        /** @description OK */
        Household: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Household"];
            };
        };
        /** @description OK */
        Settings: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        /** @description OK */
        CriteriaSet: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CriteriaSet"];
            };
        };
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A domain invariant would be violated. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description `country` or `city` */
        LevelFilter: string;
        /** @description e.g. `country.cost_of_living_index` */
        AttributeId: string;
        /** @description e.g. `country.portugal` */
        CandidateId: string;
        CriteriaSetId: string;
        EvaluationId: number;
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHousehold: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Household"];
        };
    };
    replaceHousehold: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HouseholdInput"];
            };
        };
        responses: {
            200: components["responses"]["Household"];
            400: components["responses"]["BadRequest"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Settings"];
        };
    };
    replaceSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsInput"];
            };
        };
        responses: {
            200: components["responses"]["Settings"];
            400: components["responses"]["BadRequest"];
        };
    };
    listLevels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Level"][];
                    };
                };
            };
        };
    };
    listPillars: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Pillar"][];
                    };
                };
            };
        };
    };
    listAttributes: {
        parameters: {
            query?: {
                /** @description `country` or `city` */
                level?: components["parameters"]["LevelFilter"];
                pillar?: string;
                /** @description Exclude descriptive attributes. */
                scorable_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Attribute"][];
                    };
                };
            };
        };
    };
    getAttribute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description e.g. `country.cost_of_living_index` */
                attributeId: components["parameters"]["AttributeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attribute"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listDataSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["DataSource"][];
                    };
                };
            };
        };
    };
    listCandidates: {
        parameters: {
            query?: {
                /** @description `country` or `city` */
                level?: components["parameters"]["LevelFilter"];
                parent?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Candidate"][];
                    };
                };
            };
        };
    };
    getCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description e.g. `country.portugal` */
                candidateId: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listValues: {
        parameters: {
            query?: {
                candidate?: string;
                attribute?: string;
                include_superseded?: boolean;
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Value"][];
                        total: number;
                    };
                };
            };
        };
    };
    enterValueManually: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualValueInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Value"];
                };
            };
            /** @description The attribute does not permit manual entry, or the value failed validation. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCriteriaSets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CriteriaSetSummary"][];
                    };
                };
            };
        };
    };
    createCriteriaSet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example partner */
                    id: string;
                    name: string;
                };
            };
        };
        responses: {
            201: components["responses"]["CriteriaSet"];
            409: components["responses"]["Conflict"];
        };
    };
    getCriteriaSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criteriaSetId: components["parameters"]["CriteriaSetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CriteriaSet"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCriteriaSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criteriaSetId: components["parameters"]["CriteriaSetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    renameCriteriaSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criteriaSetId: components["parameters"]["CriteriaSetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["CriteriaSet"];
        };
    };
    duplicateCriteriaSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criteriaSetId: components["parameters"]["CriteriaSetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    id: string;
                    name: string;
                };
            };
        };
        responses: {
            201: components["responses"]["CriteriaSet"];
        };
    };
    updateCriterion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criteriaSetId: components["parameters"]["CriteriaSetId"];
                /** @description e.g. `country.cost_of_living_index` */
                attributeId: components["parameters"]["AttributeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriterionInput"];
            };
        };
        responses: {
            /** @description The affected pillar, rebalanced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pillar: string;
                        criteria: components["schemas"]["EvaluationCriterion"][];
                    };
                };
            };
            /**
             * @description The change cannot be absorbed — every other weight in the pillar is locked.
             *     `code: weights_all_locked`, with the blocking locks in `details`.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updatePillarWeight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criteriaSetId: components["parameters"]["CriteriaSetId"];
                pillarId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Percentage, 0-100. Weights sum to 100 within a pillar, and pillar weights sum to 100 within a level. */
                    weight: number;
                    weight_locked?: boolean;
                };
            };
        };
        responses: {
            /** @description All pillar weights for the level, rebalanced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PillarWeight"][];
                    };
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    setMatchRuleEnforcement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criteriaSetId: components["parameters"]["CriteriaSetId"];
                matchRuleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    is_enforced: boolean;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setCompoundRuleApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criteriaSetId: components["parameters"]["CriteriaSetId"];
                compoundRuleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    is_applied: boolean;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMatchRules: {
        parameters: {
            query?: {
                /** @description `country` or `city` */
                level?: components["parameters"]["LevelFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["MatchRule"][];
                    };
                };
            };
        };
    };
    listMatchRuleResults: {
        parameters: {
            query?: {
                candidate?: string;
                match_rule?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["MatchRuleResult"][];
                    };
                };
            };
        };
    };
    putMatchRuleResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchRuleId: string;
                /** @description e.g. `country.portugal` */
                candidateId: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRuleResultInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRuleResult"];
                };
            };
        };
    };
    listCompoundRules: {
        parameters: {
            query?: {
                /** @description `country` or `city` */
                level?: components["parameters"]["LevelFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CompoundRule"][];
                    };
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Run"][];
                        total: number;
                    };
                };
            };
        };
    };
    startRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunScope"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
        };
    };
    planRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunScope"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPlan"];
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    retryRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
        };
    };
    getRanking: {
        parameters: {
            query: {
                criteria_set: string;
                level: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ranking"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listEvaluations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["EvaluationSummary"][];
                    };
                };
            };
        };
    };
    saveEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    criteria_set: string;
                    level: string;
                    /** @description Why this one was kept */
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSummary"];
                };
            };
        };
    };
    getEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluationId: components["parameters"]["EvaluationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ranking"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getCandidateScoreDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluationId: components["parameters"]["EvaluationId"];
                /** @description e.g. `country.portugal` */
                candidateId: components["parameters"]["CandidateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateScoreDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getEvaluationCriteria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluationId: components["parameters"]["EvaluationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pillar_weights: components["schemas"]["PillarWeight"][];
                        criteria: components["schemas"]["Criterion"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getComparison: {
        parameters: {
            query: {
                criteria_set: string;
                level: string;
                focus: string;
                comparators: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            /** @description Levels mixed, or more comparators than the configured limit. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listExternalScores: {
        parameters: {
            query?: {
                candidate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ExternalScore"][];
                    };
                };
            };
        };
    };
}
