-- Remove the seeded pillars and attributes.
--
-- Plain deletes. A stored value's foreign key is what makes removing an attribute that has data
-- behind it fail loudly instead of silently -- an attribute leaving the catalog is retired, not
-- deleted (arch.md 2, 7.4).

DELETE FROM attribute_source_priority     WHERE attribute IN ('country.cost_of_living_index', 'country.income_tax_effective', 'country.remote_work_tax_treaty', 'country.economic_outlook', 'country.house_price_to_income_ratio', 'country.housing_cost_overburden_rate', 'country.overcrowding_rate', 'country.international_employers', 'country.average_working_hours', 'country.tech_employment_share', 'country.statutory_paid_leave', 'country.crime_safety_index', 'country.political_economic_stability', 'country.healthcare_system_quality', 'country.climate_zone', 'country.avg_annual_temperature', 'country.annual_sunshine_hours', 'country.projected_summer_heat_days', 'country.rail_network_density', 'country.international_air_connectivity', 'country.broadband_coverage', 'country.road_network_quality', 'country.natural_diversity', 'country.protected_land_share', 'country.coastline_access', 'country.forest_cover', 'country.elevation_range', 'country.life_satisfaction', 'country.openness_to_foreigners', 'country.english_proficiency', 'country.rule_of_law', 'country.naturalisation_pathway', 'country.control_of_corruption', 'country.residency_admin_ease', 'country.press_freedom', 'country.pension_portability', 'country.school_system_quality', 'country.parental_leave_policy', 'country.child_benefit_policy');
DELETE FROM attribute_allowed_range       WHERE attribute IN ('country.avg_annual_temperature', 'country.child_benefit_policy');
DELETE FROM attribute_index_parameter     WHERE attribute IN ('country.crime_safety_index', 'country.political_economic_stability', 'country.healthcare_system_quality', 'country.openness_to_foreigners', 'country.english_proficiency', 'country.rule_of_law', 'country.control_of_corruption', 'country.press_freedom');
DELETE FROM attribute_ratio_parameter     WHERE attribute IN ('country.income_tax_effective', 'country.house_price_to_income_ratio', 'country.housing_cost_overburden_rate', 'country.overcrowding_rate', 'country.tech_employment_share', 'country.broadband_coverage', 'country.protected_land_share', 'country.forest_cover');
DELETE FROM attribute_quantity_parameter  WHERE attribute IN ('country.economic_outlook', 'country.average_working_hours', 'country.statutory_paid_leave', 'country.avg_annual_temperature', 'country.annual_sunshine_hours', 'country.projected_summer_heat_days', 'country.rail_network_density', 'country.road_network_quality', 'country.coastline_access', 'country.elevation_range', 'country.life_satisfaction', 'country.naturalisation_pathway', 'country.parental_leave_policy');
DELETE FROM attribute                     WHERE id IN ('country.cost_of_living_index', 'country.income_tax_effective', 'country.remote_work_tax_treaty', 'country.economic_outlook', 'country.house_price_to_income_ratio', 'country.housing_cost_overburden_rate', 'country.overcrowding_rate', 'country.tech_software_jobs', 'country.tech_product_jobs', 'country.international_employers', 'country.average_working_hours', 'country.tech_employment_share', 'country.statutory_paid_leave', 'country.crime_safety_index', 'country.political_economic_stability', 'country.healthcare_system_quality', 'country.climate_zone', 'country.avg_annual_temperature', 'country.annual_sunshine_hours', 'country.projected_summer_heat_days', 'country.rail_network_density', 'country.international_air_connectivity', 'country.broadband_coverage', 'country.road_network_quality', 'country.natural_diversity', 'country.protected_land_share', 'country.coastline_access', 'country.forest_cover', 'country.elevation_range', 'country.life_satisfaction', 'country.openness_to_foreigners', 'country.english_proficiency', 'country.rule_of_law', 'country.naturalisation_pathway', 'country.control_of_corruption', 'country.residency_admin_ease', 'country.press_freedom', 'country.pension_portability', 'country.school_system_quality', 'country.parental_leave_policy', 'country.child_benefit_policy');
DELETE FROM pillar                        WHERE id IN ('economics', 'housing', 'career', 'safety', 'health', 'climate', 'connectivity', 'nature', 'culture', 'governance', 'family');
