"""Two contracts, and the three things that must stay true between them.

**`docs/openapi.yaml` is the target.** Hand-written, 40 operations, deliberately ahead of the
code. It is the design, and the interface generates its typed client from it -- which is what
makes it an independent statement rather than a description of whatever the code happens to do.

**`docs/openapi.implemented.yaml` is the truth.** Generated by `make openapi` from the routes
FastAPI has, and committed, so the gap between design and reality is countable rather than
remembered.

The three checks:

1. **The generated file is fresh.** Change an endpoint without regenerating and this fails,
   because a stale file is worse than none -- it reads like a fact.
2. **Everything implemented was designed.** An endpoint invented in code is one no client knows
   about and no reviewer saw.
3. **What is implemented kept its designed identity.** The operation id is what a generated
   client names its method, so a rename is a breaking change wearing a refactor's clothes.
"""

from pathlib import Path

import pytest
import yaml

from starnest.api.document import as_yaml, served_schema

DOCS = Path(__file__).resolve().parents[3] / "docs"
DESIGN = DOCS / "openapi.yaml"
IMPLEMENTED = DOCS / "openapi.implemented.yaml"

API_PREFIX = "/v1"


def _served() -> dict:
    return served_schema()


def _operations(document: dict, *, prefix: str = "") -> dict[str, tuple[str, str]]:
    """Every operation id in a document, with the method and path it sits at."""
    return {
        operation["operationId"]: (method, path.removeprefix(prefix))
        for path, item in document["paths"].items()
        for method, operation in item.items()
        if method != "parameters" and operation.get("operationId")
    }


def _query_parameters(document: dict, *, prefix: str = "") -> dict[str, set[str]]:
    """Every operation's query parameters, by operation id.

    **Path parameters are left out, and that is a decision rather than an oversight.** They are
    part of the path shape, which `TestWhatIsImplementedKeptItsDesignedIdentity` compares with
    the names blanked for the reason given there -- and the names differ on *every one* of the
    19 parameterised operations, always as `{criteriaSetId}` against `{criteria_set_id}`. A check
    over those names would therefore fail on all 19 and report a spelling convention as drift.
    What it would catch beyond the shape check is a path parameter renamed or two of them
    transposed, and a path parameter's name reaches a client only as the label on a generated
    method's argument, because the URL is built positionally.

    A query parameter is the one that can appear in code without appearing in the design and
    change what a caller gets back while looking like nothing at all.
    """
    found: dict[str, set[str]] = {}
    for item in document["paths"].values():
        shared = item.get("parameters", [])
        for method, operation in item.items():
            if method == "parameters" or not isinstance(operation, dict):
                continue
            name = operation.get("operationId")
            if not name:
                continue
            found[name] = {
                resolved["name"]
                for parameter in [*shared, *operation.get("parameters", [])]
                for resolved in [_resolved(parameter, document)]
                if resolved.get("in") == "query"
            }
    return found


def _request_body_properties(document: dict) -> dict[str, set[str]]:
    """Every property an operation's JSON request body accepts, by operation id.

    Keyed by operation id rather than by path, so the two documents' different spellings of a
    path parameter never enter into it.

    Operations with no body, and bodies that are not `application/json`, are absent rather than
    empty: "sends nothing" and "sends an object with no fields" are different claims, and only
    the second is worth comparing.
    """
    found: dict[str, set[str]] = {}
    for item in document["paths"].values():
        for method, operation in item.items():
            if method == "parameters" or not isinstance(operation, dict):
                continue
            name = operation.get("operationId")
            body = operation.get("requestBody") if name else None
            if not body:
                continue
            schema = body.get("content", {}).get("application/json", {}).get("schema")
            if schema is not None:
                found[name] = _body_fields(schema, document)
    return found


def _required_body_fields(document: dict) -> dict[str, set[str]]:
    """Every body field an operation *demands*, by operation id.

    The companion to `_request_body_properties`, and the direction that catches the opposite
    fault. A field the design declares and the code ignores is the design being ahead, which is
    allowed. A field the code **requires** and the design does not mark required is a server
    demanding something no generated client knows it must send -- the client types it optional,
    omits it, and is answered 422 by an endpoint its own contract said it had satisfied.
    """
    found: dict[str, set[str]] = {}
    for item in document["paths"].values():
        for method, operation in item.items():
            if method == "parameters" or not isinstance(operation, dict):
                continue
            name = operation.get("operationId")
            body = operation.get("requestBody") if name else None
            if not body:
                continue
            schema = body.get("content", {}).get("application/json", {}).get("schema")
            if schema is not None:
                found[name] = _demanded(schema, document)
    return found


def _demanded(schema: dict, document: dict, *, seen: frozenset[str] = frozenset()) -> set[str]:
    """The field names one body schema requires, following `$ref` and unioning `allOf`.

    `anyOf` and `oneOf` are deliberately absent where `_body_fields` unions them: a field
    required in one branch of a choice is not required by the body, and unioning them here
    would invent demands neither document makes.
    """
    reference = schema.get("$ref")
    if reference:
        if reference in seen:
            return set()
        return _demanded(_resolved(schema, document), document, seen=seen | {reference})
    names = set(schema.get("required", []))
    for part in schema.get("allOf", []):
        names |= _demanded(part, document, seen=seen)
    return names


def _body_fields(schema: dict, document: dict, *, seen: frozenset[str] = frozenset()) -> set[str]:
    """The property names one body schema allows, following `$ref` and unioning composition.

    The two documents name their body schemas differently and always will -- the design writes
    `ManualValueInput` and Pydantic generates `ManualValueBody` -- so the comparison is over
    field names, never over the name of the schema that holds them.

    `allOf`, `anyOf` and `oneOf` are unioned, which is the direction that cannot cry wolf: a
    wider served set is more likely to flag, a wider designed set is less likely to, and a field
    the design does not mention in *any* branch is still caught. The cost is a field declared in
    one branch and served in another, which this will not notice.

    A served body with no properties at all would slip through, and is forbidden a few tests
    down by `test_every_generated_schema_describes_its_shape` -- P92 was exactly that fault.
    """
    reference = schema.get("$ref")
    if reference:
        if reference in seen:
            return set()
        return _body_fields(_resolved(schema, document), document, seen=seen | {reference})
    names = set(schema.get("properties", {}))
    for part in [*schema.get("allOf", []), *schema.get("anyOf", []), *schema.get("oneOf", [])]:
        names |= _body_fields(part, document, seen=seen)
    return names


def _resolved(parameter: dict, document: dict) -> dict:
    """A parameter, following a `$ref` into the document's own components if it is one.

    The design shares `LevelFilter`, `Limit` and `Offset` across a dozen operations, which is
    the point of components -- and a comparison that does not follow the reference reads every
    one of them as undeclared.
    """
    reference = parameter.get("$ref")
    if not reference:
        return parameter
    target: object = document
    for step in reference.removeprefix("#/").split("/"):
        if not isinstance(target, dict):
            return {}
        target = target.get(step, {})
    return target if isinstance(target, dict) else {}


@pytest.fixture(scope="module")
def served() -> dict:
    return _served()


@pytest.fixture(scope="module")
def designed() -> dict:
    return yaml.safe_load(DESIGN.read_text())


@pytest.fixture(scope="module")
def recorded() -> dict:
    return yaml.safe_load(IMPLEMENTED.read_text())


class TestTheGeneratedContractIsFresh:
    def test_regenerating_it_would_change_nothing(self) -> None:
        """`make openapi` after every endpoint change, or this fails.

        A committed file that no longer matches the code is worse than no file: it reads like a
        statement of what is served, and anyone acting on it -- a reviewer counting the gap, a
        client generator -- acts on something that stopped being true.
        """
        assert IMPLEMENTED.read_text() == as_yaml(_served()), (
            "docs/openapi.implemented.yaml is stale -- run `make openapi`"
        )

    def test_it_records_exactly_what_is_served(self, served: dict, recorded: dict) -> None:
        assert set(_operations(recorded)) == set(_operations(served))


class TestNothingIsServedThatWasNotDesigned:
    def test_no_operation_was_invented_in_code(self, served: dict, designed: dict) -> None:
        """The healthcheck is the case that makes this worth stating: `compose.yaml` calls a
        real endpoint rather than a `/health` route added for it, precisely so adding a path
        stays a change to a document with other consumers."""
        invented = set(_operations(served, prefix=API_PREFIX)) - set(_operations(designed))

        assert invented == set()

    def test_the_implemented_set_is_a_subset_of_the_design(
        self, recorded: dict, designed: dict
    ) -> None:
        assert set(_operations(recorded, prefix=API_PREFIX)) <= set(_operations(designed))

    def test_every_generated_schema_describes_its_shape(self, recorded: dict) -> None:
        """**A schema that says only "an object" describes nothing** (P92).

        Seven of them did, including Attribute, Criterion, Run and RunDetail -- the largest
        payloads this API serves. `ContractBody`'s wrap serialiser was annotated
        `-> dict[str, Any]`, and Pydantic reads a serialiser's return annotation as *the*
        serialisation schema, replacing the model's own. Every body extending that class
        documented as `{"type": "object", "additionalProperties": true}`.

        This file exists to make the gap between the design and the code countable. For a
        third of the catalog it was uncountable, and nothing said so.
        """
        schemas = recorded.get("components", {}).get("schemas", {})
        assert schemas, "the generated contract declares no schemas at all"

        shapeless = sorted(
            name
            for name, schema in schemas.items()
            if schema.get("type") == "object"
            and not schema.get("properties")
            and "$ref" not in schema
            and not schema.get("allOf")
            and not schema.get("anyOf")
        )

        assert shapeless == [], (
            f"these schemas describe nothing but their type: {shapeless}. A body that "
            "documents as a bare object is a body no consumer can generate a client for."
        )

    def test_no_query_parameter_was_invented_in_code(self, served: dict, designed: dict) -> None:
        """**Operations were compared and parameters were not** (P84).

        `/attributes` served `include_retired` for as long as it has existed and the design
        never mentioned it -- so a parameter that changes which rows a caller gets back was
        reachable, undocumented, and invisible to the one test whose job is to say what the
        gap between design and reality is. The design is deliberately ahead of the code, so a
        parameter it declares and nothing serves is fine; one the code serves and it does not
        declare is the direction this file exists to forbid.
        """
        served_parameters = _query_parameters(served, prefix=API_PREFIX)
        designed_parameters = _query_parameters(designed)

        invented = {
            name: sorted(parameters - designed_parameters.get(name, set()))
            for name, parameters in served_parameters.items()
            if parameters - designed_parameters.get(name, set())
        }

        assert invented == {}, (
            f"these operations accept query parameters the design does not declare: "
            f"{invented}. Add them to docs/openapi.yaml, or stop accepting them."
        )

    def test_no_request_body_field_was_invented_in_code(self, served: dict, designed: dict) -> None:
        """**The third place a surface can grow unnoticed**, after operations and query
        parameters.

        P84 was `/attributes` serving `include_retired` with the design silent about it. The
        request body was the half of the same gap that stayed open: this file compared what an
        operation is *called* and what it is *asked*, and never what it is *sent*. Nor does
        anything else -- `tests/acceptance/test_contract_conformance.py` validates responses,
        and its helpers read `operation["responses"]` and never `requestBody`. It posts bodies
        without ever asking whether the body the code accepts is the body the design declares.

        A body field is the worse of the two to get wrong. An undeclared query parameter is
        reachable by a client that guesses it; an undeclared body field is one the server will
        silently ignore when a client *does* send it, having typed it from the design -- or one
        the server demands and no generated client knows to send.

        The design leads, so a field it declares and nothing accepts is fine. An operation the
        design gives no body at all reads as every one of its served fields being invented,
        which is the right answer: growing a body in code is the same fault, one step larger.
        """
        served_bodies = _request_body_properties(served)
        designed_bodies = _request_body_properties(designed)

        invented = {
            name: sorted(fields - designed_bodies.get(name, set()))
            for name, fields in served_bodies.items()
            if fields - designed_bodies.get(name, set())
        }

        assert invented == {}, (
            f"these operations accept request body fields the design does not declare: "
            f"{invented}. Add them to docs/openapi.yaml, or stop accepting them."
        )

    def test_no_body_field_is_demanded_that_the_design_calls_optional(
        self, served: dict, designed: dict
    ) -> None:
        """**The one divergence of this kind that was live when this test was written.**

        `renameCriteriaSet` required `name` -- `RenameBody` declares it with no default -- and
        the design declared the property without marking it required, while both its siblings
        carry `required: [id, name]`. A rename with no name is the one thing that body cannot
        mean, so it was an omission rather than a decision, and the fix was to the design.

        This is the direction the rest of the file does not watch. Everywhere else the design
        being ahead of the code is the intended state, so "declared but not served" is never a
        failure. Required-ness inverts that: the design being *behind* on a demand is what
        breaks a caller, and it breaks it at runtime with a 422 rather than at generation time
        with a type error, which is the expensive way to find out.
        """
        served_demands = _required_body_fields(served)
        designed_demands = _required_body_fields(designed)

        undeclared = {
            name: sorted(fields - designed_demands.get(name, set()))
            for name, fields in served_demands.items()
            if fields - designed_demands.get(name, set())
        }

        assert undeclared == {}, (
            f"these operations demand request body fields the design does not mark required: "
            f"{undeclared}. A client generated from docs/openapi.yaml types them optional, "
            "omits them, and is answered 422."
        )


class TestWhatIsImplementedKeptItsDesignedIdentity:
    def test_every_served_operation_appears_in_the_design(
        self, served: dict, designed: dict
    ) -> None:
        implemented_ids = sorted(_operations(served, prefix=API_PREFIX))
        missing = [name for name in implemented_ids if name not in _operations(designed)]

        assert missing == []

    def test_every_served_operation_sits_where_it_was_designed_to(
        self, served: dict, designed: dict
    ) -> None:
        """Method and path shape, with parameter names blanked.

        The design writes `{criteriaSetId}` and the application writes `{criteria_set_id}` --
        one is a contract's spelling, the other is Python's. What must not move is how many
        parameters there are and where they sit, because a client builds the URL from the design
        and a segment out of place sends it to the wrong route.
        """
        wrong = {}
        for name in sorted(_operations(served, prefix=API_PREFIX)):
            served_method, served_path = _operations(served, prefix=API_PREFIX)[name]
            designed_method, designed_path = _operations(designed)[name]
            if (served_method, _shape_of(served_path)) != (
                designed_method,
                _shape_of(designed_path),
            ):
                wrong[name] = (served_method, served_path, designed_method, designed_path)

        assert wrong == {}


def _shape_of(path: str) -> str:
    segments = path.strip("/").split("/")
    return "/".join("{}" if segment.startswith("{") else segment for segment in segments)


def test_the_design_is_never_the_smaller_of_the_two(served: dict, designed: dict) -> None:
    """The design leads and the code follows, however small the gap becomes.

    It was 24 operations for most of the MVP and reached **zero on 2026-09-12**, when the last
    ten were built. That is the intended end state, not an error -- but the direction still
    matters: if the served set ever exceeded the design, the two files would have swapped roles
    without anyone deciding to, and `openapi.yaml` would have stopped being the thing written
    first.
    """
    assert set(_operations(served)) <= set(_operations(designed))
