"""Two contracts, and the three things that must stay true between them.

**`docs/openapi.yaml` is the target.** Hand-written, 40 operations, deliberately ahead of the
code. It is the design, and the interface generates its typed client from it -- which is what
makes it an independent statement rather than a description of whatever the code happens to do.

**`docs/openapi.implemented.yaml` is the truth.** Generated by `make openapi` from the routes
FastAPI has, and committed, so the gap between design and reality is countable rather than
remembered.

The three checks:

1. **The generated file is fresh.** Change an endpoint without regenerating and this fails,
   because a stale file is worse than none -- it reads like a fact.
2. **Everything implemented was designed.** An endpoint invented in code is one no client knows
   about and no reviewer saw.
3. **What is implemented kept its designed identity.** The operation id is what a generated
   client names its method, so a rename is a breaking change wearing a refactor's clothes.
"""

from pathlib import Path

import pytest
import yaml

from starnest.api.document import as_yaml, served_schema

DOCS = Path(__file__).resolve().parents[3] / "docs"
DESIGN = DOCS / "openapi.yaml"
IMPLEMENTED = DOCS / "openapi.implemented.yaml"

API_PREFIX = "/v1"


def _served() -> dict:
    return served_schema()


def _operations(document: dict, *, prefix: str = "") -> dict[str, tuple[str, str]]:
    """Every operation id in a document, with the method and path it sits at."""
    return {
        operation["operationId"]: (method, path.removeprefix(prefix))
        for path, item in document["paths"].items()
        for method, operation in item.items()
        if method != "parameters" and operation.get("operationId")
    }


@pytest.fixture(scope="module")
def served() -> dict:
    return _served()


@pytest.fixture(scope="module")
def designed() -> dict:
    return yaml.safe_load(DESIGN.read_text())


@pytest.fixture(scope="module")
def recorded() -> dict:
    return yaml.safe_load(IMPLEMENTED.read_text())


class TestTheGeneratedContractIsFresh:
    def test_regenerating_it_would_change_nothing(self) -> None:
        """`make openapi` after every endpoint change, or this fails.

        A committed file that no longer matches the code is worse than no file: it reads like a
        statement of what is served, and anyone acting on it -- a reviewer counting the gap, a
        client generator -- acts on something that stopped being true.
        """
        assert IMPLEMENTED.read_text() == as_yaml(_served()), (
            "docs/openapi.implemented.yaml is stale -- run `make openapi`"
        )

    def test_it_records_exactly_what_is_served(self, served: dict, recorded: dict) -> None:
        assert set(_operations(recorded)) == set(_operations(served))


class TestNothingIsServedThatWasNotDesigned:
    def test_no_operation_was_invented_in_code(self, served: dict, designed: dict) -> None:
        """The healthcheck is the case that makes this worth stating: `compose.yaml` calls a
        real endpoint rather than a `/health` route added for it, precisely so adding a path
        stays a change to a document with other consumers."""
        invented = set(_operations(served, prefix=API_PREFIX)) - set(_operations(designed))

        assert invented == set()

    def test_the_implemented_set_is_a_subset_of_the_design(
        self, recorded: dict, designed: dict
    ) -> None:
        assert set(_operations(recorded, prefix=API_PREFIX)) <= set(_operations(designed))


class TestWhatIsImplementedKeptItsDesignedIdentity:
    def test_every_served_operation_appears_in_the_design(
        self, served: dict, designed: dict
    ) -> None:
        implemented_ids = sorted(_operations(served, prefix=API_PREFIX))
        missing = [name for name in implemented_ids if name not in _operations(designed)]

        assert missing == []

    def test_every_served_operation_sits_where_it_was_designed_to(
        self, served: dict, designed: dict
    ) -> None:
        """Method and path shape, with parameter names blanked.

        The design writes `{criteriaSetId}` and the application writes `{criteria_set_id}` --
        one is a contract's spelling, the other is Python's. What must not move is how many
        parameters there are and where they sit, because a client builds the URL from the design
        and a segment out of place sends it to the wrong route.
        """
        wrong = {}
        for name in sorted(_operations(served, prefix=API_PREFIX)):
            served_method, served_path = _operations(served, prefix=API_PREFIX)[name]
            designed_method, designed_path = _operations(designed)[name]
            if (served_method, _shape_of(served_path)) != (
                designed_method,
                _shape_of(designed_path),
            ):
                wrong[name] = (served_method, served_path, designed_method, designed_path)

        assert wrong == {}


def _shape_of(path: str) -> str:
    segments = path.strip("/").split("/")
    return "/".join("{}" if segment.startswith("{") else segment for segment in segments)


def test_the_design_is_never_the_smaller_of_the_two(served: dict, designed: dict) -> None:
    """The design leads and the code follows, however small the gap becomes.

    It was 24 operations for most of the MVP and reached **zero on 2026-09-12**, when the last
    ten were built. That is the intended end state, not an error -- but the direction still
    matters: if the served set ever exceeded the design, the two files would have swapped roles
    without anyone deciding to, and `openapi.yaml` would have stopped being the thing written
    first.
    """
    assert set(_operations(served)) <= set(_operations(designed))
